import Header from 'components/Header';

import Head from 'next/head';
import * as S from './styles';

import { useCart } from 'context/useCart';
import { ComicsList } from '../components/ComicsList';

export default function Home() {
  const { cart } = useCart();

  return (
    <>
      <Head>
        <title>Marvel Comic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container>
        <Header totalCard={cart.length} />
        <ComicsList />
      </S.Container>
    </>
  );
}
